# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python

python:
 - "3.6"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
 - "pip install --upgrade pip"
 - "pip install -r requirements.txt"
 - "pip install ."
 - "git config --global user.email \"travis-user@example.com\""
 - "git config --global user.name \"Travis Userq\""

# command to run tests, e.g. python setup.py test
# script: tox
script:
 - py.test -vv --tb short

branches:
  only:
  - /^\d+\.\d+\.\d+$/
  - travis

# Not ready for this yet. travis_pypi_setup.py is in .attic
# ---------------------------------------------------------
# # After you create the Github repo and add it to Travis, run the
# # travis_pypi_setup.py script to finish PyPI deployment setup
# deploy:
#   provider: pypi
#   distributions: sdist bdist_wheel
#   user: tbarron
#   password:
#     secure: PLEASE_REPLACE_ME
#   on:
#     tags: true
#     repo: tbarron/gitr
#     condition: $TOXENV == py27
